<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voiture extends \App\Entity\Voiture implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'immatriculation' => [parent::class, 'immatriculation', null, 16],
        "\0".parent::class."\0".'marque' => [parent::class, 'marque', null, 16],
        "\0".parent::class."\0".'modele' => [parent::class, 'modele', null, 16],
        "\0".parent::class."\0".'places' => [parent::class, 'places', null, 16],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'immatriculation' => [parent::class, 'immatriculation', null, 16],
        'marque' => [parent::class, 'marque', null, 16],
        'modele' => [parent::class, 'modele', null, 16],
        'places' => [parent::class, 'places', null, 16],
        'proprietaire' => [parent::class, 'proprietaire', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
