<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trajet extends \App\Entity\Trajet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chauffeur' => [parent::class, 'chauffeur', null, 16],
        "\0".parent::class."\0".'dateDepart' => [parent::class, 'dateDepart', null, 16],
        "\0".parent::class."\0".'ecologique' => [parent::class, 'ecologique', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nbPlaces' => [parent::class, 'nbPlaces', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'villeArrivee' => [parent::class, 'villeArrivee', null, 16],
        "\0".parent::class."\0".'villeDepart' => [parent::class, 'villeDepart', null, 16],
        'chauffeur' => [parent::class, 'chauffeur', null, 16],
        'dateDepart' => [parent::class, 'dateDepart', null, 16],
        'ecologique' => [parent::class, 'ecologique', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nbPlaces' => [parent::class, 'nbPlaces', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'villeArrivee' => [parent::class, 'villeArrivee', null, 16],
        'villeDepart' => [parent::class, 'villeDepart', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
