<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyilh3G\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyilh3G/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHyilh3G.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHyilh3G\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHyilh3G\App_KernelProdContainer([
    'container.build_hash' => 'Hyilh3G',
    'container.build_id' => '068e0f87',
    'container.build_time' => 1747665292,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyilh3G');
