nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/':
            allow_origin: ['http://127.0.0.1:5500']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Type', 'Authorization']
            max_age: 3600
            allow_credentials: true
